####
# Env vars are, in order:
# DEPLOY_KEY
# CAPISTRANO_DEPLOY_USER
# CAPISTRANO_DEPLOY_PATH_TO_SSH_KEY
# CAPISTRANO_PRODUCTION_DEPLOY_TO
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

language: ruby
cache:
  bundler: true
  directories:
  - "/home/travis/.rvm"
rvm:
- 2.1.5
install: bundle install --jobs=3 --retry=3 --without deploy production
before_script:
- mysql -e 'create database footprints_test;'
- cp config/ci.database.yml config/database.yml
- cp config/mailer.yml.example config/mailer.yml
script: bundle exec rake
jobs:
  include:
  - stage: test
  - stage: deploy
    script: skip
    deploy:
      provider: script
      script: "./travis-deploy.sh"
stages:
- name: test
- name: deploy
  on: |
    branch IS master AND \
    env(TRAVIS_PULL_REQUEST) IS NOT true
env:
  global:
  - secure: VFPTYjs9qySaJ5eE3w63gSfpcKIfFTcR4MxgJQUB5J+uEAsuDGFXFyiJkJSEwT6Y4u46KsA+uMeQ8f9NdYpfx8EpytJ5UYZzJgo5XdmGftggy4rQHkz3FLLlHBDtJGIoVTIJIjJKb9g6IzrX/yx/YGUX34aNrOh+LaJDIDo7bLZx6TZ+1QXhIWF/t2HG8wDL0GD0gyezt5tqxiPObKFQc/XUr1fKvbdrE4sUqVa+45JaKXcfuYWDwjI0xXrEMOSBp10v/jClD17HBKOibbnTk8D5iWuJdPIWZoaRRXNGanPv80UlarEG3E7NPoss5kVc3fkrmL5r1z73LQc6CZvBOkzJ0K6Dnf+Wylw8r2nHV7D3Ek1cf/jTeVagLS23ZhvqVzHRPAuo6jA9ZemJxo7uDM7qKSIcfaPhf4WKFDaevEQHOqTCBYuQ3Xt4yj7YPFsMlfMUUm7G6ZH7t70OwpG6CCYxDdD+BeNboC60dGK5ijqGhE5FyBunO4J+ZAEThP4nsMNGjI5H2osv0J0Z46Drgskf3haXPbdTUlpGkbFhvTUt0W/B+YjDSYi60ukM7S0y2uPFPi7c4Zcm9+oUR6fJ7vDXp9ZjpR4mKbFyexpcO2yRdOgrogTJHK5iOJhpqi7wtzb0xS2N3XLjgpRDtihtDsNTlf8sij0Zz+Gfra43RR0=
  - secure: xHh+xMvA6xbUufBmmyNsDEZG4ZGpVIRK+UeRBSASaseEVlKmbPlHOnGDbwhZxhCyk4/95CBybZyGMJvatsD/buqoSo3pjRwaRzANtHsmmj90LQ6749H+2t0wblKJEvmZ48B7i9Ix1m11uCged3YeYuyGjVFYvigY5ZvyNdV+UX3csEKawPX3kX2XHwSdxwRAsV8s/bqcx4L46hL16/dLLW74U6J2lzAuG8YATm9MEPez04h5b29c6GDceDahrnNrLhcK83OhIafpVdXzjxYLzqrx527kUC8jF0MXkdKczkCggDAHL+GV0MHJKhct/ONL7CDrcWPt90ButmLyxrpyBDublE0KnIXJHe5KtOanFLkstQZG0cf6KBHACVbDTTodhwMUZ7UMgsMusZyRuEBdFctQvMuLAFqGtVmSjestDCSFhogbWc34alWvuvsYeaxdPTGOBqUwjhhlaDldw22hN8SBgPEdvrkikYJDxE8KkRH1x9UByT4o9XvGDLBYr3CPZcQNMakf0pDh88D/UhHfzujOAm5vOEITlLETObfcW6FppHdV5WRFiQqVmuKqekmuwqUzgFY9g1o//OyUv/50XulbIyct2UzGOkiSrMDp7PIBSO5J71Qws20WI5iG4VodlmJ+KeLkz7eC7vL4g6m79aNNV1lcvJh33uv//PLk5fE=
  - secure: aYx+9kQ12oC3mgJD0+UgKVk3hNAOk4U4UZ4yjcER0vDA5foyucgZFzBHTaS/JtQplUn/allEWRo3+6OUrhZzDifMCzZtLEKs2rWhBT/Qbn189E17qyz5OnuWbOgu3FHpV86yMLbLu/6zAZIDg+4uQuNnP4QD2ocQLxn/3gpC4YogcruR9EDviD7tAkz88Wb1y7Ha7rFot/qL3QL3X6nl0CmuF6hcH3AtO+lUStAvV/bQ0derEjadINtlo6+M3VL5bjzFSCQsfwbDeSNPlbK4mdTFVXd8X90yfEYEiYonNar1QKNTt5ZaJR0bl3oPngYclhBh0N9DxrR3njf0n4tnmf1kz9Qtqwo1uzX5n6/tl/JMvfFkhVQo416zf7hFudnHO2xc5MCidgnC+uJESECC+KvaUXTJRSUWYQnjKlIiEWTfxw0KBVR21kBU0Uh2AmQAo6ibOynG9RMVPzjosH9aRTNPlWW0cyL9ncBcc6T68C30AiGvJORsxQ/bFy69pLbAiNsDuNkACP+VxW6OtTk6SE4nnBETaVeWTmCKD3lEL1tGkwl9+2iquGutc9PtOX4YPPa+so+yZb+E23s2NTnX39dNAUZh0h8Soe4PqvArIEjwHJX4YQ/lG/g0bX9NGBrbtI627ICdAqJ9mWvupA4y+2R1o6XKLjnoJPErv/7Uh7o=
  - secure: bBY4kJHC150TOTGMF6IwWK6d14YVOZIEQqdP9R31KQ1jewSMi+/Bih3nF4UxV0ArdnmLdGNHl2+lecR1bW6Rbu5NZT6FNiJOcFzP+c/zjxt47YnC/nNMoVJVUTQ3VABMZi14Meqz2NBCD8tyYFrj8+17Udx8YtFh5MWWEZUhWdFV9RmE4DvNbdjjrnIid6C1kjUkgWIFLE1ukmb+hEelzLwTLUc4V66jDTPrxmDp8n2HscU/yKTH8t5UdIuI0Lddz7zgbZ0uiLI4WQQgoJql1SpE1lca/DNE/Ixsl6J60EhddU04JR0WIdR2gSjp4euUkteFpowdqL3yN49HH7OA/QTcyCkiqvolvEaepgDzZOeVZtE2FIZSOt8hjzbMnChzBlrkZJm7UZ7amBczMslRUekWqCVQKt+kC+GkqYtCevuKoQH0rM47+iOR5iUlVAGSpPY8Grh1jd4A/IaFvT7PukjHMCPnJ84CGjS7gmR0AqvUVwt2fRFqOvtiH7RtX9oEVDPOVwEn1J8ih0Xvcg+qnWDzdtURJqn6eHnDS7AhyXb2vCAUTnTAXV1LSPA5YHmK84e54XrZTtLpBVGyu5yp8EOdknikf3wxBZiTHVsPN0VBxskyxfZa+2TNwd2Uws002ItA5HclLo3Z9K8ZP822Nu5lIfD9/jopszxOYnXss/U=
  - secure: AnTnCyPOPI362+b4m0FpJL9qvotiMzOiAuey5OeG9fVa6NdHN8Fbd9HnrN0RvnDUT8QvZxkjCwm4jPjwcThzqY8r205FYiLoX+Lsg1Kwn1LRvC+5/9Pcd09AvXK8rZyFkmkOdh86vr7nMBDpWv7ATQyz/FaX+g0R9zM/MUnI5/dZPK8AKspHYSN3ZQvfguhLr1xDWdiVxFXEPtw9/uBVJxaRQFHxCX1oIF7GOcfM3zg3ngTIlrpx2YEq6/te/N39IuQAmSoI9xIw5Ci9IrpFA+WR18bEubYr4uC2VKnvULjJrGd01gvbaPMV4+nWB5uAGrwGasA/a25AjX7Bv798w7eaA4OOEvisRPa6YLfi6GDFAJJNcp38zqak0TO89veGm77XYiz7zXDAiPeUAkxWeUAtoRBUZWJ9MuF/qnFH4Yr4KVK3jimfBKdT9+map4sY9ynkta/qfDy55UmMf0MV/NX6DO7n9j6WE+2QbZvV+r5UrgQGnORZOTMfgvrhvCR6ffwjNhVoL49HmnBflBKcGS60moliuueHcG6E4bE+cUJiR8Wq1bbOd721pCZ+g9opkXMzJb2rvyG4WJ8NuXbDaOn7wxYUovd8gnpYmJ/HQsl1jS9KVNDDy9eQGwMLNBe7ehjGPUqyxJ8SIn1u2zwePI9zh1izcNoAK+kSpn8BYCo=
  - secure: mDo1F/pPUien6X/ZnT8LRnR70IrX5sW1yuvg1YP4Je19X04gAE60JeCWJV4e2bSJi1ii8PKy+iI6TJ1/lfebb/Ehx2j0sDQkCGHHqjoVCOjpuCVCF5BAQQTs+5EFf2eVQwZWVajY1OvwU/6NwhHDIbp4Au08Ii19VseOk+jVRStMvReDed85K831GL0wzkqXKBA/P4RKjT+hZEy4XTPO79PUYO4NS6PqUeRpl2TlYv0kmnOw0Ean4OWBBcC0+9X6vg55m89PBfeCKGSV/kbZ8I1ATMMLeNf7a+h36NcOGdufPOBY0eiK3Mq+1maMJRSwOj6JApXcfUJxXLcey0671EIgsa5ZZHxVWnGtv/l/iXjXMnNkjmmx934924I/oYOq/BBUBK1UCKrKuObe5uUs9XGyF3KLMMcz2jPgIoRF5eAZIasTeq2mii/8CHztO1n39hRfoporS6pJ1mP7jJeHbau1oXXMCuWUVr1A1eaWmsmijqbIBXu/6cY7GMqfGHMc6Fv94Gc1O2cfAzaa6siCnYqcssuRUEimYpSCGl5V5tVBr2lM4x/lsHivpHCasnpbU3koXeB++erMc9ZPwoUWCPprsdQzLlWBsVTD70o1xp5HvTGKfxO4nFtdzo+T7VWeN6O2SnLL2s/uN7o5BxL1CCXM6jEjryrO8kUvqqes9wU=
